<?php

/**
 * @file
 * Contains multibanners.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function multibanners_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.multibanners':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Layout-configurable multibanner blocks composed of banner entities.') . '</p>';
      return $output;
    default:
  }
}

/**
 * Implements hook_preprocess_block().
 */
function multibanners_preprocess_block(&$variables) {
  if ($variables['elements']['#plugin_id'] === 'views_block:multibanners-banner_block') {
    $variables['#attached']['library'][] = 'multibanners/unslider';
  }
}

/**
 * Implements hook_theme().
 */
function multibanners_theme() {
  return array(
    'banner' => array(
      'file' => 'banner.page.inc',
      'render element' => 'elements',
      'template' => 'banner',
    ),
  );
}
